---
title: "Vincent's CV"
author: Vincent Bellavance
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/styles.css', 'resume', 'https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css']
    self_contained: true
    includes: 
      after_body: ["assets/preloader.js", "assets/google-analytics.js"]
---

```{r, include=FALSE, cache = F}
knitr::opts_chunk$set(
  results='asis',
  echo = FALSE
)

library(glue)
library(tidyverse)


# Holds all the links that were inserted for placement at the end
PDF_EXPORT <- FALSE

source('R/parsing_functions.R')

# Load csv with position info
position_data <- readr::read_csv('data/positions.csv')
```


Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-paper-plane" style="color:#FFFFFF;" ></i> <a href="mailto:vincent.bellavance@insileco.io">vincent.bellavance@insileco.io</a>
- <i class="fa fa-github" style="color:#FFFFFF;"></i> [VincentBellavance](https://github.com/VincentBellavance)
<!-- - <i class="fa fa-globe"></i> -->
<!-- - <i class="ai ai-google-scholar"></i> [Publications](https://scholar.google.com/citations?user=GyChlIoAAAAJ&hl=en)-->
- <i class="ai ai-orcid" style="color:#a9c518;"></i> [0000-0002-3263-8784](https://orcid.org/0000-0002-3263-8784)

<br>

Quantitative skills
------------------------------------

Hierarchical models,<br>Bayesian statistics,<br>Spatio-temporal models

<br>

Programming
------------------------------------

<span style="font-weight:600;">Data analysis</span>: R, HPC, bash<br>

<span style="font-weight:600;">Database</span>: PostgreSQL, DuckDB<br>

<span style="font-weight:600;">Automation/reports</span>: <br>Quarto/R Markdown/Markdown, <br> LaTeX<br>

<span style="font-weight:600;">Web</span>: HTML/CSS, Javascript, <br> Shiny App 

<span style="font-weight:600;">Reproducibility</span>: Git, GitHub Actions, Docker

<br>

Languages
------------------------------------

**French**<span style="font-size:11px;"> Native</span><br>
**English**<span style="font-size:11px;"> Full Professional</span><br>


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with [**pagedown**](https://github.com/rstudio/pagedown).

The source code is available at [github.com/VincentBellavance/cv](https://github.com/VincentBellavance/cv).

Last updated on `r Sys.Date()`.

[<i class='fas fa-download' style="color:#FCEF7E;"></i> Download a PDF of this CV](https://VincentBellavance.github.io/cv/VincentBellavance.pdf)


Main
================================================================================

 <span style="font-weight:600">Vincent Bellavance</span> <span style="font-size: 13px;">M.Sc.</span>{#title}
--------------------------------------------------------------------------------


<span style="font-size: 1rem;">< <i class="fa fa-chart-bar"></i> + <i class="fa fa-robot"></i> >  Data scientist </span>


Professionnal Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'professional_positions')
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'education')
```


Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'teaching_positions')
```


Training {data-icon=certificate}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'training')
```
